@_bal_stack_guard = external global i8*
!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!3}
!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = !DIFile(filename:"../../../compiler/testSuite/08-import/type2-v.modules/mod/notempty.bal", directory:"../../../compiler/testSuite/08-import/type2-v.modules/mod")
!2 = !DIFile(filename:"../../../compiler/testSuite/08-import/type2-v.modules/mod/empty.bal", directory:"../../../compiler/testSuite/08-import/type2-v.modules/mod")
!3 = distinct !DICompileUnit(language: DW_LANG_C99, file: !1, isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, splitDebugInlining: false)
!4 = !DISubroutineType(types: !5)
!5 = !{}
