// These should be generated from build.bal

#define PANIC_ARITHMETIC_OVERFLOW 1
#define PANIC_DIVIDE_BY_ZERO 2
#define PANIC_TYPE_CAST 3
#define PANIC_STACK_OVERFLOW 4
#define PANIC_INDEX_OUT_OF_BOUNDS 5
#define PANIC_LIST_TOO_LONG 6
#define PANIC_STRING_TOO_LONG 7
#define PANIC_LIST_STORE 8
#define PANIC_MAPPING_STORE 9
#define PANIC_NO_FILLER 10
#define PANIC_INTERNAL_ERROR 11
#define PANIC_IMPOSSIBLE_DIVIDE 12
