[package]
org = "wso2"
name = "nballerina"
version = "0.1.0"
[build-options]
observabilityIncluded = false

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-platform-1.5.9-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/llvm-platform-15.0.6-1.5.9-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-linux-x86_64.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-linux-arm64.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-windows-x86_64.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-macosx-arm64.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-android-arm.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-android-x86_64.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-ios-arm64.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-linux-armhf.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-macosx-x86_64.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-android-arm64.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-android-x86.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-windows-x86.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-linux-ppc64le.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-ios-x86_64.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-linux-x86.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/llvm-15.0.6-1.5.9-SNAPSHOT-linux-arm64.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/llvm-15.0.6-1.5.9-SNAPSHOT-windows-x86.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/llvm-15.0.6-1.5.9-SNAPSHOT-macosx-x86_64.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/llvm-15.0.6-1.5.9-SNAPSHOT-linux-x86.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/llvm-15.0.6-1.5.9-SNAPSHOT-linux-x86_64.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/llvm-15.0.6-1.5.9-SNAPSHOT-windows-x86_64.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/llvm-15.0.6-1.5.9-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/llvm-15.0.6-1.5.9-SNAPSHOT-linux-armhf.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/llvm-15.0.6-1.5.9-SNAPSHOT-linux-ppc64le.jar"
