[package]
org = "wso2"
name = "nballerina.regex"
version = "0.1.0"

[[dependency]]
org = "wso2"
name = "nballerina"
version = "0.1.0"
repository = "local"

[build-options]
observabilityIncluded = true
