name: Validate on jBallerina 2201.1.x nightly

on:
  schedule:
    - cron: '15 */12 * * *'
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get run ID
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'LATEST_RUN_ID<<EOF' >> $GITHUB_ENV
          gh run list --workflow daily-build-2201.1.x.yml --repo ballerina-platform/ballerina-distribution | grep success | head -n 1 | awk '{print $(NF-2)}' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Download jBallerina
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run download ${{ env.LATEST_RUN_ID }} -D "$HOME" --name "Linux Installer deb" --repo ballerina-platform/ballerina-distribution
      - name: Install jBallerina
        run: |
          sudo dpkg -i ~/ballerina*.deb
          echo "JAVA=/usr/lib/ballerina/dependencies/jdk-11.0.8+10-jre/bin/java" >> $GITHUB_ENV
      - name: Test
        run: |
          make -j2 test
      - name: Archive test ouput
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test output
          path: |
            test/out
